### ISSUE TITLE
Radio Button Group and Select widgets not working

### ISSUE THREAD

**Issue by swelshh** [Wakanda/wakanda-issues#19]
Build: 11.194922
OS: 10.10.4

When working on a Page in Studio, the "Radio Button Group" and "Select" widgets in the "Form Controls" area are greyed out:

![screen shot 2015-12-11 at 8 54 39 am](https://cloud.githubusercontent.com/assets/1295707/11746692/dcb897bc-9fe4-11e5-9dd6-1a943c4c887d.png)

When I try to use one of them I get the following error:

![screen shot 2015-12-11 at 8 55 12 am](https://cloud.githubusercontent.com/assets/1295707/11746721/f158a20c-9fe4-11e5-8036-cb253ccfcea4.png)

**Comment by hamzahik** [comment]
Fixed in https://github.com/Wakanda/RadioGroup/commit/dcbf9a58afe7fbbfe93cb96b8767a4e6b78c2101
https://github.com/Wakanda/Select/commit/88c68a73ba00b385161247fbd7454f87e9470c59

Will be included in Wakanda 1.0.1

**Comment by swelshh** [comment]
Awesome, thanks!

**Comment by hamzahik** [comment]
@swelshh wakanda community 1.0.1 containing the fix is available for download on wakanda.org

**Comment by swelshh** [comment]
Hi @hamzahik, I'm working in 11.195328 and the problem is still there.  Is there another version I could be using?

**Comment by swelshh** [comment]
No wait, sorry @hamzahik.  It is working.  These two widget still seem ghosted (ie greyed out) in the list of widgets.  But they can be drag/dropped onto a page.
