### ISSUE TITLE
[4D Mobile] Scope "publicOnServer" is ignored when set on data class of non-merged model

### ISSUE THREAD

**Issue by liuxiang625** [Wakanda/wakanda-issues#240]
4D Version: V16.3
Wakanda Build: Enterprise 2.4.0
OS: Mac OS 10.13.3

**Steps to Reproduce:**

1. Create a new 4D database and add a new table named "Person".
2. Create a new Wakanda solution and connect to the 4D database. uncheck the option of "Merge with active Model".
3. Add following code to model.js of remote model:
`model.Person.properties.scope = "publicOnServer";
model.Person.FirstName.scope = "publicOnServer";`
4. Start Wakanda Server.
5. Access datastore using URL [http://127.0.0.1:8081/rest/UnMergedRemoretModel/Person](http://127.0.0.1:8081/rest/UnMergedRemoretModel/Person).

**Expected behavior:**
Can not access data class Person using REST access because it is set to Public on server.

**Actual behavior:**
Person class is still accessible from client side despite the scope change. However, the scope set on attribute "FirstName" works, the attribute is removed from REST access. See screenshot below:
![screen shot 2018-02-13 at 4 59 54 pm](https://user-images.githubusercontent.com/1305420/36182620-5bf63526-10df-11e8-8019-e50d2eff4763.png)

The scope of the data class is showing as "Public on Server" in the studio:
![screen shot 2018-02-13 at 4 35 37 pm](https://user-images.githubusercontent.com/1305420/36182642-7a46b7d0-10df-11e8-961a-1264900b0b8e.png)

As I tested, this bug **only** happens when setting the scope of data class of non-merged model. The scope property works on attributes of non-merged model and merged model.

Sample test database and solution attached:

[ScopeOnUnMergedTable.zip](https://github.com/Wakanda/wakanda-issues/files/1722264/ScopeOnUnMergedTable.zip)

**Comment by JegoYann** [comment]
Thanks @liuxiang625 . We've reproduce the issue.

**Comment by JegoYann** [comment]
Hello @liuxiang625 ,
This issue is fixed with v2.5.0

Regards,
Yann

**Comment by liuxiang625** [comment]
Hi Yann,

Thanks for fixing the issue and notifying me of the update.

I just tested 2.5.0 with V16.3 on Mac 10.13.4. It appears the issue is not fixed, I can still access "Person" data class when its scope is set to "PublicOnServer" in an unmerged model. Please see the screen shots below. Let me know if there is any change I should apply in my code.
![screen shot 2018-04-20 at 9 48 16 am](https://user-images.githubusercontent.com/1305420/39063438-fc82d016-447f-11e8-9ae2-be28649b6b0d.png)

![screen shot 2018-04-20 at 9 44 31 am](https://user-images.githubusercontent.com/1305420/39063378-c5dde352-447f-11e8-8801-5eb2d0084923.png)

![screen shot 2018-04-20 at 9 44 37 am](https://user-images.githubusercontent.com/1305420/39063375-c5c5353c-447f-11e8-8631-7b83be29b8f9.png)

**Comment by JegoYann** [comment]
Hello Xiang,
Here is my test with a 4D remote model unmerged in Wakanda Server v2.5.0. The `cars` dataclass is `publicOnServer` as expected.

As you only show the Studio version, Maybe your studio is pointing to an old server ? 

![screen shot 2018-04-23 at 15 11 56](https://user-images.githubusercontent.com/3337770/39128758-eb4ff374-4708-11e8-8072-aa5f915d89be.png)

**Comment by liuxiang625** [comment]
Hi Yann,

My 2.5.0 studio is indeed pointing to 2.4.0 server. It works as expected when I changed it to 2.5.0.
I will notify the customer of this fix.

Thanks for fixing the bug and following up in this issue.
Xiang

**Comment by liuxiang625** [comment]
One more question, the github release page: https://github.com/Wakanda/wakanda-digital-app-factory/releases currently only has source code of 2.5.0, the built download is not available yet. Do you know when can the customer download a public release of 2.5.0 Enterprise?
